timer:
  time:
target:
  enderDragon: false
  wither: false
gamerule:
  ultraHardCore: false
  ultraUltraHardCore: false
  splitHearts: false
  lifeScoreTab: false
  allowDie: false
  damageMessage: false
  damageMultiplier: 1
  prottime: 0
  noXP: false
  noSneak: false
  noJump: false
  noCrafting: false

